title: Gabriel Katzeff
description: A website to host a repository of projects to showcase the skills gained throughout my experiences and studies 
remote_theme: pages-themes/leap-day@v0.2.0
plugins: jekyll-remote-theme
